### ISSUE TITLE
CubesViewer Server is slow to get saved views and also while saving & sharing views

### ISSUE THREAD

**Issue by voldesh** [jjmontesl/cubesviewer#74]
cubesviewer-server takes almost a minute to save and get the views.
Optimization needed.

**Comment by jjmontesl** [comment]
1. Could you provide reproduction steps? When is it exactly getting stuck, what are the steps?
2. How many views are there in the database?
3. Have you checked if your database is involved? Does this happen if you access view objects via the administration backend? (http://yourhost:8000/admin, and enter the password you entered when initializing the database).

**Comment by voldesh** [comment]
I started the cubesviewer Django server.
Then, I started the slicer server.
Now, I went to the website where I hosted it.
And when I clicked on the button "Cubes", it takes some time to get me the list of available cubes from my cubes model.
Plus, when I try to save the opened view, it takes about a minute to save it.
And when I refresh and try to look at all the available Saved Views, it then takes a time to get me that.
Being too slow getting me the views.

It is taking too much time to get even 1 saved view.

**Comment by jjmontesl** [comment]
I cannot reproduce this. 

I'd need a trace of network requests made from the browser (ie a screenshot of Chrome development tools showing the Network XHR requests involving loading and saving, and showing sizes and times).

Also please answer points 2 and 3 above (number of views, and whether this happens from the CubesViewer Server administration backend).

Ultimately, if possible, I might need access to this installation to troubleshoot this.

**Comment by voldesh** [comment]
![screenshot from 2016-06-13 13 59 10](https://cloud.githubusercontent.com/assets/19408767/16001402/5e989248-316f-11e6-95f9-e36a6edc6326.png)

info request takes much longer time. It sits pending and until that Cubes are not showing in the browser.

Point 2. I am using 1 view.

Point 3. No, I have not tried.

**Comment by jjmontesl** [comment]
The request that is slow (~8.5 sec) is the `info` request made to Cubes.

The problem does not seem related to CubesViewer, but to the Cubes installation. Please answer the following questions:

1. Where is your Cubes Server deployed? (is it also localhost?)
2. What is the value of the settings.py keys: `CUBESVIEWER_CUBES_URL` and `CUBESVIEWER_BACKEND_URL`.
3. Try accessing your Cubes server directly: `http://localhost:5000/info` . If that takes a long time, the problem is definitely with the Cubes installation.

**Comment by voldesh** [comment]
1. Tried the cubes server on both localhost as well as on an address in the VPN.
2. values are changed as per being on localhost or a different address.
3. /info gives pretty quick results. That isn't the issue, I think.

I was experimenting yesterday and found that Firefox loads /info pretty quick, while Chrome takes a while on localhost as well as an address in the VPN.

**Comment by voldesh** [comment]
Issue solved by adding processes:10 in server section of slicer. Now, it works fast on both localhost as well as on different address.

**Comment by jjmontesl** [comment]
Happy to hear it's solved.

The issue actually was caused because Cubes *testing* server (slicer serve) accepts only one simultaneous request by default, which you can increase with `processes`. Browsers keep a connection open for a while (HTTP KeepAlive) so you could not access Cubes server from another client.

The workaround is ok, but *for production purposes* remember that you should front Cubes with a proper web server (like Apache or Nginx), since the 10 connections limit will hit you sooner or later.

**Comment by voldesh** [comment]
Yes, you are correct on that part. Thank you !

Additionally, isn't that processes thing be in the docs ?
